sebarickert/financer

frontend/.eslintrc, frontend/package-lock.json, frontend/package.json, frontend/postcss.config.js, frontend/public/index.html, frontend/src/App.tsx, frontend/src/Financer.tsx, frontend/src/Login.tsx, frontend/src/assets/tailwind.css, frontend/src/components/button/button.tsx, frontend/src/components/container/container.tsx, frontend/src/components/form/form.footer.tsx, frontend/src/components/form/form.header.tsx, frontend/src/components/form/form.tsx, frontend/src/components/hero/hero.tsx, frontend/src/components/input/input.tsx, frontend/src/components/layout/layout.tsx, frontend/src/components/select/select.tsx, frontend/src/index.tsx, frontend/src/pages/Accounts.tsx, frontend/src/pages/accounts/Accounts.tsx, frontend/src/pages/accounts/AccountsRouter.tsx, frontend/src/pages/accounts/AddAccount.tsx, frontend/src/utils/addLeadingZero.ts, frontend/tailwind.config.js
#7 
`/accounts`
`/accounts/add`
=> Accounts page skeleton (Page + Form)

backend/src/controllers/account-controller.ts, backend/src/routes/account-route.ts, backend/src/services/account-service.ts
go to http://localhost:3000/api/account and in console
```
fetch('/api/account/YOUR-ACCOUNT-ID', {
method: 'DELETE',
headers: {
'Accept': 'application/json',
'Content-Type': 'application/json'
}
})
fetch('/api/account/YOUR-ACCOUNT-ID', {
method: 'PUT',
headers: {
'Accept': 'application/json',
'Content-Type': 'application/json'
},
body: JSON.stringify({
name: "modified name",
type: "credit",
balance: -1000.00
})
})
```
=> Add modify and delete endpoints to account api

backend/src/controllers/expense-controller.ts, backend/src/controllers/income-controller.ts, backend/src/index.ts, backend/src/routes/expense-route.ts, backend/src/services/transaction-service.ts, shared-types/transaction.d.ts
check http://localhost:3000/api/expense you should not have any expenses
get some account id from http://localhost:3000/api/account and run code below
```
fetch('/api/expense', {
method: 'POST',
headers: {
'Accept': 'application/json',
'Content-Type': 'application/json'
},
body: JSON.stringify({
fromAccount: "YOUR-ACCOUNT-ID",
amount: 10,
description: "test",
date: new Date()
})
})
```
=> Init expense endpoints

backend/src/controllers/account-controller.ts, backend/src/controllers/transaction-controller.ts, backend/src/routes/expense-route.ts, backend/src/routes/income-route.ts, backend/src/services/transaction-service.ts
get expense id from http://localhost:3000/api/expense view single expense http://localhost:3000/api/expense /EXPENSE-ID
get income id from http://localhost:3000/api/income view single expense http://localhost:3000/api/income/INCOME-ID
```
fetch('/api/income/EXPENSE-ID', {
method: 'DELETE',
headers: {
'Accept': 'application/json',
'Content-Type': 'application/json'
},
})
fetch('/api/expense/EXPENSE-ID', {
method: 'DELETE',
headers: {
'Accept': 'application/json',
'Content-Type': 'application/json'
},
})
```
=> Add delete and view single expense/income

.github/workflows/validate-main-branches.yml, frontend/src/components/button/button.tsx, frontend/src/components/dashboard-stats/dashboard.stats.tsx, frontend/src/components/form/form.tsx, frontend/src/components/navigation/desktop/navigation.desktop.tsx, frontend/src/components/navigation/navigation.container.tsx, frontend/src/components/navigation/navigation.logo.tsx, frontend/src/pages/accounts/AccountForm.tsx, frontend/src/pages/accounts/AccountTransfer.tsx, frontend/src/pages/accounts/Accounts.tsx, frontend/src/pages/dashboard/Dashboard.tsx, frontend/src/pages/expenses/EditExpense.tsx, frontend/src/pages/expenses/ExpenseForm.tsx, frontend/src/pages/expenses/Expenses.tsx, frontend/src/pages/income/EditIncome.tsx, frontend/src/pages/income/IncomeForm.tsx, frontend/src/pages/income/Incomes.tsx, frontend/src/utils/formatCurrency.ts, frontend/src/utils/formatDate.ts, frontend/tsconfig.json
=> Dashboard stats, button focus ring updates

packages/frontend/src/components/monthly-summary-graph/monthly-summary-graph.tsx, packages/frontend/src/hooks/transaction/useAllTransactions.ts
https://github.com/recharts/recharts/issues/1738#issuecomment-882061128
=> Fix statistics page rendering

package-lock.json, packages/frontend/package.json, packages/frontend/src/components/balance-graph/balance-graph.tsx, packages/frontend/src/components/dashboard-stats/dashboard.stats.item.tsx, packages/frontend/src/components/dashboard-stats/dashboard.stats.tsx, packages/frontend/src/components/description-list/description-list.item.tsx, packages/frontend/src/components/heading/heading.tsx, packages/frontend/src/components/icon/icon.documentReport.tsx, packages/frontend/src/components/icon/icon.tsx, packages/frontend/src/components/link-list/link-list.button.tsx, packages/frontend/src/components/transaction-stacked-list/transaction-stacked-list.row.tsx
=> Update dashboard styles

packages/frontend/src/components/blocks/form/form.footer.tsx
=> Fix form footer background

packages/backend/src/modules/transactions/transactions.service.ts
=> FIx monthly summary logic

packages/frontend/src/hooks/transaction/useFirstTransaction.ts
=> Fix transaction list month change logic

docker/Dockerfile
=> Fix production build

.github/actions/test-frontend/action.yml, .github/workflows/build-docker.yml, .github/workflows/pr.yml, .github/workflows/push-production.yml
=> Fix pipeline

packages/frontend/containers/transition.provider.tsx, packages/frontend/pages/_app.tsx
=> Add animations for browser navigatikon events

packages/frontend/src/components/blocks/balance-graph/balance-graph.tsx, packages/frontend/src/components/blocks/dashboard-stats/dashboard.stats.tsx, packages/frontend/src/components/blocks/monthly-summary-graph/monthly-summary-graph.tsx, packages/frontend/src/pages/accounts/account.balance-history-chart.tsx, packages/frontend/src/pages/settings/categories/category.tsx
=> Fix app crashing

packages/frontend/containers/expenses/expense.add.container.tsx, packages/frontend/src/components/blocks/dashboard-stats/dashboard.stats.tsx, packages/frontend/src/components/blocks/details-list/details-list.tsx, packages/frontend/src/components/blocks/transaction-categories/transaction-categories.form.tsx, packages/frontend/src/components/blocks/transaction-form/transaction-form.tsx, packages/frontend/src/components/blocks/transaction-template-switcher/transaction-template-switcher.tsx, packages/frontend/src/components/elements/select/select.tsx, packages/frontend/src/constants/months.ts, packages/frontend/src/pages/accounts/account.form.tsx, packages/frontend/src/pages/accounts/account.tsx, packages/frontend/src/pages/settings/categories/category.form.tsx, packages/frontend/src/pages/settings/templates/template.form.tsx, packages/frontend/src/utils/formatDate.ts, packages/playwright/tests/expenses/add-expense-category.spec.ts, packages/playwright/tests/incomes/add-income-category.spec.ts, packages/playwright/tests/transaction-categories/categories-in-transaction-forms.spec.ts
=> Bug hunting

packages/frontend/src/components/blocks/balance-graph/balance-graph.tsx, packages/frontend/src/components/blocks/monthly-summary-graph/monthly-summary-graph.tsx, packages/frontend/src/constants/graph/chartjs.d.ts, packages/frontend/src/constants/graph/graph.settings.ts, packages/frontend/src/utils/formatCurrency.ts
=> Chart tooltip

.github/actions/prepare-node-job/action.yml
This pull request includes a minor change to the `runs:` section in the `.github/actions/prepare-node-job/action.yml` file. The change corrects a syntax error in the `key` value by removing an extra single quote in the `hashFiles` function.
=> Fix type in CI pipeline

.github/workflows/build-docker.yml
=> Update docker registry environment variable

.github/actions/prepare-node-job/action.yml
=> Update cache paths for CI action

packages/backend/package.json, packages/frontend/package.json
=> Fix docker build

docker/Dockerfile, package-lock.json
=> Fix docker build part2

packages/frontend/src/pages/settings/templates/template.listing.tsx
=> Fix template listing page

packages/backend/prisma/schema.prisma, packages/backend/src/modules/auth/strategies/auth0.stategy.ts
=> Hotfix user schema issues

docker/docker-compose.development.yml, kubernetes/production.db-deployment.yaml
=> Update mongodb version latest

.vscode/settings.json, packages/backend/src/modules/accounts/accounts.controller.spec.ts, packages/backend/src/modules/accounts/dto/account.dto.ts, packages/backend/src/modules/expenses/expenses.controller.spec.ts, packages/backend/src/modules/transaction-categories/dto/transaction-category.dto.ts, packages/backend/src/modules/transaction-categories/transaction-categories.controller.spec.ts
=> Fix skipped tests

.github/workflows/deploy-dev.yml, .github/workflows/push-production.yml
=> Fix secret name

.github/actions/build-docker-image/action.yml, .github/actions/publish-docker-image/action.yml, .github/actions/test-playwright/action.yml
=> Update docker file

.github/workflows/static-analyze.yml, packages/backend/sonar-project.properties, packages/frontend/sonar-project.properties, packages/playwright/sonar-project.properties, sonar-project.properties
=> Add static analyze

.github/actions/publish-docker-image/action.yml, .github/workflows/push-production.yml
=> Disable build cache

packages/backend/src/database/repos/transaction.repo.ts, packages/backend/src/modules/account-balance-changes/dto/account-balance-change.dto.ts, packages/backend/src/modules/accounts/accounts.service.ts, packages/backend/src/modules/transaction-category-mappings/transaction-category-mappings.service.ts, packages/backend/src/modules/transaction-templates/dto/transaction-template-log.dto.ts, packages/backend/src/modules/transaction-templates/transaction-templates.service.ts, packages/backend/src/modules/transactions/dto/transaction.dto.ts, packages/backend/src/modules/transactions/transactions.service.ts, packages/backend/src/utils/date.service.ts
=> Fix monthly summary calculations

packages/backend/src/modules/tasks/tasks.service.ts, packages/backend/src/modules/transaction-templates/transaction-templates.service.ts, packages/backend/src/utils/date.service.ts
=> Fix creating automated transactions

kubernetes/production.webapp-deployment.yaml, packages/frontend/middleware.ts
This pull request includes several changes to the Kubernetes deployment configuration and a minor change to the frontend middleware. The most important changes include updating the Docker image references, modifying environment variable configurations, and adjusting health check paths.
* Updated Docker image references for both backend and frontend containers to use the new repository `ghcr.io/sebarickert/financer:latest` (`kubernetes/production.webapp-deployment.yaml`) [[1]](diffhunk://#diff-6041904ac06c88f0e4c425efa9f11ffd7ec98a0f2888bbcbcae88d49f7bf665bL23-R23) [[2]](diffhunk://#diff-6041904ac06c88f0e4c425efa9f11ffd7ec98a0f2888bbcbcae88d49f7bf665bL55-R55).
* Changed environment variable configuration for the frontend container from using `envFrom` to explicit `env` variables …
=> Fix frontend health check

packages/frontend/src/views/dashboard/dashboard.tsx
This pull request to `packages/frontend/src/views/dashboard/dashboard.tsx` includes changes to enhance the dashboard view by adding new components and cleaning up the code. The most important changes include importing new components and updating the JSX structure to display these components.
Enhancements to the dashboard view:
* [`packages/frontend/src/views/dashboard/dashboard.tsx`](diffhunk://#diff-9406da7264e7bfabccc1e1f1d71d3fffb2b9817fbf6aa2834295a884e40e9bf9R1-R4): Added imports for `BalanceGraph` and `DashboardStats` components.
* [`packages/frontend/src/views/dashboard/dashboard.tsx`](diffhunk://#diff-9406da7264e7bfabccc1e1f1d71d3fffb2b9817fbf6aa2834295a884e40e9bf9L10-R17): Updated the JSX structure to include `DashboardStats` and `BalanceGraph` components within a section.
=> Fix dashboard

packages/frontend/src/components/layouts/header/header.tsx, packages/frontend/src/components/layouts/layout/layout.tsx
This pull request includes several updates to improve the responsiveness and styling of the `Header` and `Layout` components in the frontend. The changes primarily focus on refining class names and ensuring better behavior on different screen sizes.
* [`packages/frontend/src/components/layouts/header/header.tsx`](diffhunk://#diff-93db57373d1b260704a669b4c755ac7b6b7154f3caac0bb901e90e8c34cf1bcbL25-R31): Refined class names for better readability and responsiveness. Adjusted the `z-index` property to be specific to smaller screens.
* [`packages/frontend/src/components/layouts/layout/layout.tsx`](diffhunk://#diff-a93983aa66e389ee4de983af3fa2d25ab95b2a8c4c55964b3a6ac4ec79828b02L28-R28): Modified the `Container` component to apply `overflow-y-scroll` only on smaller screens.
* …
=> Some fixes

.vscode/settings.json, packages/frontend/middleware.ts, packages/frontend/src/components/blocks/balance-graph/balance-graph.tsx, packages/frontend/src/components/blocks/dashboard-stats/dashboard.stats.tsx, packages/frontend/src/components/blocks/transaction-listing/transaction-listing.container.tsx, packages/frontend/src/components/layouts/header/header.tsx, packages/frontend/src/redux/api/emptyFinancerApi.ts, packages/frontend/src/redux/api/financerBaseQuery.ts, packages/frontend/src/ssr/accounts/get-total-balance.ts, packages/frontend/src/ssr/get-server-data.ts, packages/frontend/src/ssr/get-session-id.ts, packages/frontend/src/ssr/user-preferences/get-dashboard-settings.ts, packages/frontend/src/utils/address.helper.ts, packages/frontend/src/utils/is-server-side.ts, packages/frontend/src/views/dashboard/dashboard.tsx, packages/frontend/tsconfig.path.json
This pull request includes several changes to improve the frontend codebase, focusing on refactoring, server-side rendering enhancements, and configuration updates. The most important changes include refactoring the middleware to use a helper function, updating server-side data fetching logic, and adding new utility functions.
* [`packages/frontend/middleware.ts`](diffhunk://#diff-665ab7ff283bca1800a7a21236ebc289133599b4990b74835c263be11e6b66efL3-R3): Refactored to use the `getInternalApiRootAddress` helper function instead of the inline `getBackendAddress` function. [[1]](diffhunk://#diff-665ab7ff283bca1800a7a21236ebc289133599b4990b74835c263be11e6b66efL3-R3) [[2]](diffhunk://#diff-665ab7ff283bca1800a7a21236ebc289133599b4990b74835c263be11e6b66efL28-R27)
* …
=> Refactor seo

packages/frontend/src/components/blocks/navigation/navigation.desktop.item.tsx, packages/frontend/src/components/blocks/toast/toast.container.tsx, packages/frontend/src/components/layouts/header/header.tsx, packages/frontend/src/components/layouts/layout/layout.tsx
This pull request includes several changes to the frontend components, primarily focusing on adding the `'use client'` directive and simplifying the `Layout` component by removing unnecessary imports and usage.
* [`packages/frontend/src/components/blocks/navigation/navigation.desktop.item.tsx`](diffhunk://#diff-877ba86485979899e0b65dc28d6364dfaafff98342c20fd8e10c59ca415bc71eL1-R10): Added `'use client'` directive and reordered imports.
* [`packages/frontend/src/components/blocks/toast/toast.container.tsx`](diffhunk://#diff-aab0d29dda857fa13a45394eebcd5e44081008c905adb9d3d94de4f65592e49bR1-R2): Added `'use client'` directive.
* [`packages/frontend/src/components/layouts/header/header.tsx`](diffhunk://#diff-93db57373d1b260704a669b4c755ac7b6b7154f3caac0bb901e90e8c34cf1bcbR1-R2): Added `'use …
=> Remove global loader

packages/frontend/app/(application)/page.tsx, packages/frontend/src/redux/api/financerBaseQuery.ts
=> Cache fix test

packages/frontend/app/layout.tsx, packages/frontend/app/login/page.tsx, packages/frontend/containers/root.provider.tsx, packages/frontend/src/components/blocks/balance-graph/balance-graph.tsx, packages/frontend/src/ssr/api/authentication.service.ts, packages/frontend/src/views/login/login.tsx, packages/frontend/tailwind.config.js
This pull request to `packages/frontend` includes significant updates to the authentication flow, layout, and some minor code cleanups. The most important changes include adding authentication checks to the `RootLayout`, creating a dedicated login page, and updating the `RootProviderContainer` to handle onboarding and authentication errors.
* [`packages/frontend/app/layout.tsx`](diffhunk://#diff-4b6159cf554f19576156f9876685abafc89589cd09c2664f26475ed8c1a8ebd6R2-R12): Added authentication checks and redirects for unauthenticated users and users without accounts. [[1]](diffhunk://#diff-4b6159cf554f19576156f9876685abafc89589cd09c2664f26475ed8c1a8ebd6R2-R12) [[2]](diffhunk://#diff-4b6159cf554f19576156f9876685abafc89589cd09c2664f26475ed8c1a8ebd6L31-R62) …
=> Move root redirects to SSR side

packages/frontend/src/components/blocks/pager/pager.tsx, packages/frontend/src/components/blocks/transaction-listing-with-monthly-pager/transaction-listing.with.monthly-pager.tsx
=> Fix month pager layout

packages/frontend/containers/accounts/account.add.container.tsx, packages/frontend/containers/accounts/account.delete.container.tsx, packages/frontend/containers/accounts/account.edit.container.tsx, packages/frontend/containers/accounts/account.update-market-value.container.tsx, packages/frontend/containers/categories/category.add.container.tsx, packages/frontend/containers/categories/category.edit.container.tsx, packages/frontend/containers/expenses/expense.add.container.tsx, packages/frontend/containers/expenses/expense.edit.container.tsx, packages/frontend/containers/incomes/income.add.container.tsx, packages/frontend/containers/incomes/income.edit.container.tsx, packages/frontend/containers/settings/override-user-data.container.tsx, packages/frontend/containers/templates/template.add.container.tsx, packages/frontend/containers/templates/template.edit.container.tsx, packages/frontend/containers/transfers/transfer.add.container.tsx, packages/frontend/containers/transfers/transfer.edit.container.tsx, packages/frontend/src/hooks/settings/user-preference/useDashboardSettings.ts, packages/frontend/src/hooks/settings/user-preference/useDefaultMarketUpdateSettings.ts, packages/frontend/src/hooks/settings/user-preference/useStatisticsSettings.ts, packages/frontend/src/hooks/settings/user-preference/useUserDefaultExpenseAccount.ts, packages/frontend/src/hooks/settings/user-preference/useUserDefaultIncomeAccount.ts, packages/frontend/src/hooks/settings/user-preference/useUserDefaultTransferSourceAccount.ts, packages/frontend/src/hooks/settings/user-preference/useUserDefaultTransferTargetAccount.ts, packages/frontend/src/hooks/settings/user-preference/useUserTransactionListChunkSize.ts, packages/frontend/src/ssr/api/transaction.service.ts
This pull request includes several changes across multiple containers to ensure that relevant caches are cleared after certain actions. The most important changes involve adding cache-clearing functions to various account, category, expense, income, template, and transfer containers.
* **Accounts:**
- Added `clearAccountCache` after account creation and deletion in `AccountAddContainer` and `DeleteAccountContainer`. (`packages/frontend/containers/accounts/account.add.container.tsx` [[1]](diffhunk://#diff-4d466f528962f5dd34aa21e6e36cb1232719bfb7932c1bdf581ae62fbb414e01R26) `packages/frontend/containers/accounts/account.delete.container.tsx` [[2]](diffhunk://#diff-48bc3ba8179a8e749664aadfc0ca8a6c6bb31a9d5883ca88536ad3166227e6caR23)
- Ensured `clearAccountCache` is called after account …
=> Clear SSR cache after CSR mutation

CONTRIBUTING.md, README.md, docker/docker-compose.production.yml, kubernetes/development.webapp-deployment.yaml, packages/frontend/src/components/blocks/HardRefreshButton.tsx, packages/frontend/src/components/blocks/transaction-listing-with-monthly-pager/transaction-listing.with.monthly-pager.summary.tsx, packages/frontend/src/components/blocks/transaction-listing/transaction-listing.tsx, packages/frontend/src/components/pages/error-page/error-page.tsx, packages/frontend/src/utils/formatCurrency.ts, packages/frontend/src/views/settings/settings.tsx
=> Some minor bugfixes

packages/backend/src/middlewares/http-access-log.middleware.ts
=> Add health check endpoint to ignore pattern in HttpAccessLogMiddleware

packages/backend/src/middlewares/http-access-log.middleware.ts, packages/backend/src/modules/system/system.controller.ts
=> Minor fixes

packages/frontend/src/components/blocks/drawer/drawer.tsx, packages/frontend/src/components/blocks/form/form.footer.tsx, packages/frontend/src/components/blocks/navigation/navigation.mobile.tsx, packages/frontend/src/components/layouts/header/header.tsx, packages/frontend/src/components/layouts/layout/layout.tsx
=> Minor improvements vol 123

packages/frontend/src/components/blocks/navigation/navigation.mobile.tsx, packages/frontend/src/components/layouts/header/header.tsx, packages/frontend/src/components/layouts/layout/layout.tsx
=> Revert vt changes

packages/frontend/src/utils/transitionAnimations.ts
=> Improve view transitions part 1

packages/backend/prisma/schema.prisma, packages/backend/src/database/repos/account-balance-change.repo.ts, packages/backend/src/database/repos/account.repo.ts, packages/backend/src/database/repos/system-log.repo.ts, packages/backend/src/database/repos/transaction-category-mapping.repo.ts, packages/backend/src/database/repos/transaction-category.repo.ts, packages/backend/src/database/repos/transaction-template-log.repo.ts, packages/backend/src/database/repos/transaction-template.repo.ts, packages/backend/src/database/repos/transaction.repo.ts, packages/backend/src/database/repos/user-preferences.repo.ts, packages/backend/src/database/repos/user.repo.ts, packages/backend/src/modules/transaction-categories/__snapshots__/transaction-categories.service.spec.ts.snap, packages/backend/src/modules/transaction-categories/dto/transaction-month-summary.dto.ts, packages/backend/src/modules/transaction-categories/transaction-categories.controller.ts, packages/backend/src/modules/transaction-category-mappings/__snapshots__/transaction-category-mappings.service.spec.ts.snap, packages/backend/src/modules/transaction-category-mappings/transaction-category-mappings.service.ts, packages/backend/src/modules/transactions/__snapshots__/transactions.service.spec.ts.snap, packages/backend/src/modules/transactions/dto/transaction-month-summary.dto.ts, packages/backend/src/modules/transactions/transactions.service.ts, packages/backend/src/types/force-mutable.ts, packages/frontend/src/redux/schema/api-spec.json, packages/playwright/tests/transaction-categories/transaction-category-analytics.spec.ts
=> Refactor category mapping summary backend logic

packages/frontend/src/assets/tailwind.css, packages/frontend/src/components/blocks/drawer/drawer.header.tsx, packages/frontend/src/components/blocks/drawer/drawer.tsx, packages/frontend/src/components/blocks/header-drawer-action/header-drawer-action.tsx, packages/frontend/src/components/blocks/navigation/navigation.mobile.actions.tsx, packages/frontend/src/components/blocks/transaction-categories/transaction-categories.tsx, packages/frontend/src/components/blocks/transaction-template-switcher/transaction-template-switcher.tsx, packages/frontend/src/components/elements/button/button.tsx, packages/frontend/src/views/accounts/account.update-market-value.tsx
=> Implemenet native drawer

packages/frontend/public/manifest.json
Reverts sebarickert/financer#325
=> Revert "Update manifest.json"

packages/frontend/src/components/blocks/transaction-categories/transaction-categories.form.tsx
=> fix categories submit issues

.github/workflows/pr.yml, .github/workflows/push-production.yml
=> Fix push main CI

packages/backend/src/config/configuration.ts, packages/backend/src/config/database-server.ts, packages/frontend/src/assets/tailwind.css, packages/frontend/src/components/blocks/transaction-form/transaction-form.tsx, packages/frontend/src/components/elements/select/select.tsx
=> Implement experimental selectlist

packages/frontend/app/layout.tsx, packages/frontend/containers/accounts/account.container.tsx, packages/frontend/containers/categories/category.container.tsx, packages/frontend/containers/statistics/statistics.container.tsx, packages/frontend/src/components/blocks/ThemeSwitcher/ThemeSwitcher.tsx, packages/frontend/src/components/blocks/balance-graph/balance-graph.tsx, packages/frontend/src/ssr/api/user.service.ts
=> Fix non logged in user root layout view mode fetching

packages/frontend/app/issues-with-login/page.tsx, packages/frontend/app/privacy-policy/page.tsx, packages/frontend/src/assets/tailwind.css, packages/frontend/src/components/blocks/ThemeSwitcher/ThemeSwitcherItem.tsx, packages/frontend/src/components/blocks/TransactionTypeSwitcher/TransactionTypeSwitcherItem.tsx, packages/frontend/src/components/blocks/transaction-categories/transaction-categories.form.tsx
=> Focus to focus-visible

packages/frontend/src/components/blocks/Navigation/Navigation.tsx, packages/frontend/src/components/blocks/Navigation/NavigationCreateTransactionButton.tsx, packages/frontend/src/components/blocks/Navigation/NavigationItem.tsx, packages/frontend/src/components/blocks/TransactionFormSwitcher.tsx, packages/frontend/src/components/blocks/drawer/drawer.header.tsx
=> Fix transaction default account usage

packages/frontend/src/components/blocks/ProminentLink.tsx, packages/frontend/src/components/blocks/Transaction.tsx, packages/frontend/src/components/blocks/TransactionList/TransactionListItem.tsx, packages/frontend/src/components/blocks/drawer/drawer.header.tsx, packages/frontend/src/components/elements/Link.tsx, packages/frontend/src/views/accounts/account.tsx, packages/frontend/src/views/settings/categories/category.tsx
=> Fix link haptic

packages/frontend/app/layout.tsx, packages/frontend/src/components/elements/Heading.tsx, packages/frontend/src/views/login/login.tsx
=> Tweak Heading sizing in mobile and themeColor fix

packages/frontend/src/assets/tailwind.css, packages/frontend/src/components/blocks/TransactionFormSwitcher.tsx, packages/frontend/src/components/blocks/TransactionTemplateSwitcher.tsx, packages/frontend/src/components/blocks/TransactionTypeSwitcher/TransactionTypeSwitcher.tsx, packages/frontend/src/components/blocks/TransactionTypeSwitcher/TransactionTypeSwitcherItem.tsx, packages/frontend/src/components/blocks/drawer/drawer.header.tsx, packages/frontend/src/components/blocks/drawer/drawer.tsx, packages/frontend/src/components/blocks/transaction-categories/transaction-categories.tsx
=> Tweak transaction form

packages/frontend/containers/root.provider.tsx, packages/frontend/src/components/blocks/ScrollToTop.tsx, packages/frontend/src/components/elements/Popper.tsx
=> Tweaks vol 123

.github/actions/test-playwright/action.yml, .github/workflows/pr.yml, .github/workflows/push-production.yml, packages/playwright/playwright.config.ts
=> Fix e2e test CI reporting

packages/frontend/src/components/blocks/dashboard-stats/dashboard.stats.tsx, packages/frontend/src/components/elements/ProminentDetailItem.tsx, packages/frontend/src/features/transaction/TransactionList/TransactionListItem.tsx, packages/frontend/src/features/transaction/TransactionListWithMonthlyPager/TransactionListWithMonthlySummary.tsx, packages/frontend/src/views/Transaction.tsx, packages/frontend/src/views/user-preferences/UserDashboardSettingsForm.tsx, packages/frontend/src/views/user-preferences/UserDefaultAccountSettingsForm.tsx, packages/frontend/src/views/user-preferences/UserDefaultMarketUpdateSettingsForm.tsx, packages/frontend/src/views/user-preferences/UserStatisticsPageSettingsForm.tsx, packages/playwright/assets/fixture-data.json, packages/playwright/tests/user-preferences/user-preferences.spec.ts, packages/playwright/utils/account/getAccountBalanceFromAccountListByName.ts, packages/playwright/utils/account/getAccountDataFromAccountList.ts, packages/playwright/utils/account/getAccountDetails.ts, packages/playwright/utils/applyFixture.ts, packages/playwright/utils/category/getCategoryDataFromCategoryList.ts, packages/playwright/utils/category/getCategoryDetails.ts, packages/playwright/utils/common/clickPopperItem.ts, packages/playwright/utils/dashboard/getDashboardDetails.ts, packages/playwright/utils/statistics/getStatisticsDetails.ts, packages/playwright/utils/template/deleteTemplate.ts, packages/playwright/utils/template/getTemplateDataFromTemplateList.ts, packages/playwright/utils/transaction/fillAndSubmitTransactionTemplateForm.ts, packages/playwright/utils/transaction/getTransactionDataFromTransactionList.ts, packages/playwright/utils/transaction/getTransactionDetails.ts, packages/playwright/utils/transaction/switchTransactionType.ts
=> Add user preference tests

.github/workflows/push-production.yml
=> Fix main CI pipeline

.github/actions/build-app/action.yml, .github/actions/static-analyze/action.yml, .github/actions/test-jest/action.yml, packages/frontend/src/components/elements/button/button.test.tsx
=> Fix type test ts

packages/backend/sonar-project.properties, packages/frontend/sonar-project.properties
=> Fix sonar config

.github/workflows/pr.yml
=> Fix PR pipeline

packages/frontend/src/assets/tailwind.css, packages/frontend/src/components/blocks/List.tsx, packages/frontend/src/components/blocks/Logo.tsx, packages/frontend/src/components/blocks/Navigation/Navigation.tsx, packages/frontend/src/components/blocks/Navigation/NavigationItem.tsx, packages/frontend/src/components/blocks/drawer/drawer.tsx, packages/frontend/src/components/elements/Link.tsx, packages/frontend/src/components/layouts/Header.tsx, packages/frontend/src/components/layouts/Layout.tsx, packages/frontend/src/constants/graph/graph.settings.ts
=> tweak colors a bit

packages/frontend/app/layout.tsx, packages/frontend/src/assets/tailwind.css, packages/frontend/src/components/elements/Heading.tsx, packages/frontend/src/components/elements/chart/chart-wrapper.tsx, packages/frontend/src/components/layouts/ContentHeader.tsx, packages/frontend/src/components/layouts/Layout.tsx, packages/frontend/src/constants/graph/graph.settings.ts
=> Tune colors

packages/playwright/playwright.config.ts
=> Remove mobile_safari as it is flaky, but keep webkit

packages/frontend/app/(application)/accounts/[accountId]/edit/page.tsx, packages/frontend/app/(application)/accounts/[accountId]/page.tsx, packages/frontend/app/(application)/settings/categories/[categoryId]/edit/page.tsx, packages/frontend/app/(application)/settings/categories/[categoryId]/page.tsx, packages/frontend/app/(application)/settings/templates/[templateId]/edit/page.tsx, packages/frontend/app/(application)/settings/user-preferences/dashboard-settings/page.tsx, packages/frontend/app/(application)/settings/user-preferences/default-account-settings/page.tsx, packages/frontend/app/(application)/settings/user-preferences/market-update-settings/page.tsx, packages/frontend/app/(application)/settings/user-preferences/maximum-items-per-page/page.tsx, packages/frontend/app/(application)/settings/user-preferences/statistics-settings/page.tsx, packages/frontend/app/(application)/statistics/expenses/[expenseId]/edit/page.tsx, packages/frontend/app/(application)/statistics/expenses/[expenseId]/page.tsx, packages/frontend/app/(application)/statistics/expenses/page.tsx, packages/frontend/app/(application)/statistics/incomes/[incomeId]/edit/page.tsx, packages/frontend/app/(application)/statistics/incomes/[incomeId]/page.tsx, packages/frontend/app/(application)/statistics/incomes/page.tsx, packages/frontend/app/(application)/statistics/transfers/[transferId]/edit/page.tsx, packages/frontend/app/(application)/statistics/transfers/[transferId]/page.tsx, packages/frontend/app/(application)/statistics/transfers/page.tsx, packages/frontend/app/layout.tsx
=> Update metadatas to be dynamic

.github/actions/test-playwright/action.yml, .github/workflows/pr.yml, .github/workflows/push-production.yml, packages/frontend/src/assets/tailwind.css, packages/frontend/src/components/elements/select/select.tsx
=> Update select element to work custom-ish and normal

packages/frontend/src/assets/tailwind.css, packages/frontend/src/components/blocks/drawer/drawer.tsx
=> Add pointer-events control for popover and update drawer component

packages/frontend/containers/categories/CategoryListingContainer.tsx, packages/frontend/containers/settings/UserPreferencesContainer.tsx, packages/frontend/src/assets/tailwind.css, packages/frontend/src/components/blocks/List.tsx, packages/frontend/src/components/blocks/dashboard-stats/dashboard.stats.tsx, packages/frontend/src/components/elements/chart/chart-wrapper.tsx, packages/frontend/src/components/layouts/Layout.tsx, packages/frontend/src/features/account/AccountList.tsx, packages/frontend/src/features/template/TemplateList.tsx, packages/frontend/src/features/transaction/TransactionList/TransactionList.tsx, packages/frontend/src/features/transaction/TransactionList/TransactionListItem.tsx, packages/frontend/src/features/transaction/TransactionListWithMonthlyPager/TransactionListWithMonthlySummary.tsx, packages/frontend/src/views/Account.tsx, packages/frontend/src/views/Category.tsx, packages/frontend/src/views/Dashboard.tsx, packages/frontend/src/views/Login.tsx, packages/frontend/src/views/Settings.tsx, packages/frontend/src/views/Transaction.tsx
=> small ui tweaks

packages/frontend/src/assets/tailwind.css, packages/frontend/src/components/elements/Select.tsx, packages/frontend/src/features/transaction/TransactionCategories/TransactionCategories.tsx
=> hotfix select element bleeding edge plaaplaa

package-lock.json, packages/frontend/package.json, packages/frontend/src/components/blocks/List.tsx, packages/frontend/src/components/blocks/ProminentLink.tsx, packages/frontend/src/components/blocks/RadialStackedChart.tsx, packages/frontend/src/components/blocks/pager/pager.tsx, packages/frontend/src/components/elements/Popper.tsx, packages/frontend/src/constants/transaction/transactionTypeMapping.ts, packages/frontend/src/features/account/AccountList.tsx, packages/frontend/src/features/transaction/TransactionList/TransactionListItem.tsx, packages/frontend/src/features/transaction/TransactionListWithMonthlyPager/TransactionListWithMonthlyPager.tsx, packages/frontend/src/features/transaction/TransactionListWithMonthlyPager/TransactionListWithMonthlySummary.tsx, packages/playwright/utils/statistics/getStatisticsDetails.ts
=> Install recharts and add RadialStackedChart for statistics page

packages/frontend/src/features/transaction/TransactionListWithMonthlyPager/TransactionListWithMonthlyPager.tsx
=> Add z-index for absolute positioned buttons

packages/backend/src/modules/accounts/accounts.controller.spec.ts, packages/backend/src/modules/accounts/accounts.controller.ts, packages/backend/src/modules/accounts/accounts.service.ts, packages/backend/src/modules/expenses/expenses.controller.ts, packages/backend/src/modules/incomes/incomes.controller.ts, packages/backend/src/modules/transactions/transactions.controller.ts, packages/backend/src/modules/transfers/transfers.controller.ts, packages/backend/src/utils/validate-array.pipe.ts, packages/backend/src/utils/validate-enum.pipe.ts
=> Add backend validators to fix weird issue with accountTypes

packages/frontend/src/components/blocks/pager/pager.service.ts, packages/frontend/src/features/transaction/TransactionListWithMonthlyPager/TransactionListWithMonthlyPager.tsx
=> Update pager to support future dates if present

packages/frontend/src/components/blocks/Form.tsx
=> Fix button sizing issue

packages/frontend/containers/accounts/AccountListingContainer.tsx, packages/frontend/src/assets/tailwind.css, packages/frontend/src/components/charts/CustomTooltip.tsx, packages/frontend/src/components/charts/PieChartDonut.tsx, packages/frontend/src/features/account/AccountTypeBalanceChart.tsx, packages/frontend/src/types/ChartData.ts
=> Account combined balance chart

packages/frontend/src/constants/statisticsContextualNavigationItems.ts
=> fix bufix bug

Dockerfile
=> Install rsync

packages/frontend/src/components/layouts/ContentHeader.tsx
=> Fix content header issue on mobile

packages/frontend/src/components/layouts/ContentHeader.tsx, packages/frontend/src/components/layouts/Header.tsx, packages/frontend/src/utils/transitionAnimations.ts, packages/frontend/src/views/Transaction.tsx
=> Add media breakpoint for sliding animation

packages/frontend/src/assets/tailwind.css
=> maybe fix dark mode

packages/frontend/src/assets/tailwind.css
=> test stuff

package-lock.json, package.json, packages/frontend/package.json, packages/frontend/postcss.config.js, packages/frontend/src/assets/tailwind.css
=> Refactor package configuration and remove unused postcss-mixins

.vscode/settings.json, packages/frontend/src/assets/tailwind.css
=> Enhance Tailwind CSS configuration and improve dark/light mode styles

packages/frontend/app/privacy-policy/page.tsx, packages/frontend/src/assets/tailwind.css, packages/frontend/src/components/blocks/ContextualNavigation.tsx, packages/frontend/src/components/blocks/Navigation/NavigationItem.tsx, packages/frontend/src/components/blocks/ProminentLink.tsx, packages/frontend/src/components/blocks/ThemeSwitcher/ThemeSwitcherItem.tsx, packages/frontend/src/components/elements/InputOption.tsx, packages/frontend/src/components/elements/Link.tsx, packages/frontend/src/components/elements/Popper.tsx, packages/frontend/src/components/elements/Select.tsx, packages/frontend/src/components/layouts/ContentHeader.tsx, packages/frontend/src/features/account/AccountList.tsx, packages/frontend/src/features/account/AccountTypeRadio.tsx, packages/frontend/src/features/transaction/TransactionCategories/TransactionCategories.tsx, packages/frontend/src/features/transaction/TransactionCategories/TransactionCategoriesItem.tsx, packages/frontend/src/features/transaction/TransactionList/TransactionListItem.tsx, packages/frontend/src/features/transaction/TransactionTypeSwitcher/TransactionTypeSwitcherItem.tsx
=> Enhance hover and active styles for various components

packages/frontend/containers/accounts/AccountListingContainer.tsx, packages/frontend/containers/categories/CategoryListingContainer.tsx, packages/frontend/containers/settings/SettingsContainer.tsx, packages/frontend/src/components/blocks/Drawer.tsx, packages/frontend/src/components/blocks/InfoMessageBlock.tsx, packages/frontend/src/components/elements/Heading.tsx, packages/frontend/src/components/elements/Popper.tsx, packages/frontend/src/features/account/AccountList.tsx, packages/frontend/src/features/template/TemplateList.tsx, packages/frontend/src/features/transaction/TransactionCategories/TransactionCategories.tsx, packages/frontend/src/features/transaction/TransactionList/GroupedTransactionList.tsx, packages/frontend/src/features/transaction/TransactionListWithMonthlyPager/TransactionListWithMonthlyPager.tsx, packages/frontend/src/features/transaction/TransactionListWithMonthlyPager/TransactionListWithMonthlySummary.tsx, packages/frontend/src/views/Transaction.tsx
=> update spacings a bit

packages/playwright/utils/transactions/getTransactionsDetails.ts
=> Spacing update

packages/frontend/src/components/blocks/BalanceDisplay.tsx, packages/frontend/src/components/blocks/Card/Card.tsx, packages/frontend/src/components/blocks/Card/CardHeader.tsx, packages/frontend/src/components/blocks/InfoMessageBlock.tsx, packages/frontend/src/features/transaction/TransactionList/GroupedTransactionList.tsx, packages/frontend/src/features/transaction/TransactionList/TransactionList.tsx, packages/frontend/src/features/transaction/TransactionList/TransactionListItem.tsx, packages/frontend/src/features/transaction/TransactionListWithMonthlyPager/TransactionListWithMonthlyPager.tsx, packages/frontend/src/views/Dashboard.tsx
=> Add transaction lists into a card with title

packages/frontend/src/constants/transaction/TRANSACTION_TYPE_MAPPING.ts, packages/frontend/src/constants/transaction/transactionTypeMapping.ts, packages/frontend/src/features/category/CategoryForm.tsx, packages/frontend/src/features/dashboard/DashboardBalanceSummary.tsx, packages/frontend/src/features/transaction/TransactionForm.tsx, packages/frontend/src/features/transaction/TransactionList/TransactionListItem.tsx, packages/frontend/src/features/transaction/TransactionListWithMonthlyPager/TransactionListWithMonthlySummary.tsx, packages/frontend/src/features/transaction/TransactionTypeIcon.tsx, packages/frontend/src/views/Transaction.tsx, packages/frontend/src/views/user-preferences/UserDefaultAccountSettingsForm.tsx
=> Refactor transaction type mappings for improved clarity and consistency

helm/Chart.lock, helm/Chart.yaml, helm/values.yaml
=> Fix helm setup

README.md, helm/templates/postgress-backup.cron-job.yaml, helm/values.yaml
=> Update PostgreSQL configuration for backup and restore processes

package-lock.json, packages/backend/package.json, packages/backend/src/app.module.ts, packages/backend/src/instrument.ts, packages/backend/src/main.ts
=> Setup sentry

.github/workflows/pr.yml
=> Disable docker cache for PR build

.github/actions/deploy/action.yaml, .github/workflows/push-main.yml
=> Setup deploy action

.github/workflows/push-main.yml
=> fix ci thingy:x!

.github/workflows/pr.yml, .github/workflows/push-main.yml, helm/values.yaml, packages/frontend/sentry.client.config.ts
=> Add sentry env configs

packages/frontend/next.config.js
=> Update Sentry project name to 'financer-frontend' in Next.js config

.github/workflows/push-main.yml
=> Fix deploy step

packages/backend/src/modules/auth/guards/auth0.guard.ts, packages/backend/src/modules/auth/strategies/auth0.stategy.ts, packages/backend/src/modules/auth/strategies/github.stategy.ts
=> Add scope options to Auth0Guard for enhanced authentication

packages/frontend/src/components/Breadcrumbs.tsx, packages/frontend/src/components/UserMenu.tsx, packages/frontend/src/views/Dashboard.tsx
=> Trim transitions
